""""Add accessible_without_login to Book model"

Revision ID: 47955b177ec4
Revises: 
Create Date: 2024-12-05 00:23:09.487731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47955b177ec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accessible_without_login', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('accessible_without_login')

    # ### end Alembic commands ###
